
// Generated by https://quicktype.io

export interface FormsTypeSchema {
  result: Result;
}

export interface Result {
  schemasList: SchemasList[];
}

export interface SchemasList {
  type: string;
  display: string;
}

export interface SelectionOption {
  value: string, label: string
}

export interface FormDetails {
  [key: string]: FormEnum | FormType | FormDetails
}

export interface FormEnum {
  type: 'Enum';
  enumValues: string[]
}

export interface FormType {
  type: 'String' | 'Date' | 'Enum';
  require?: boolean;
}

export interface FormTypeEnum extends FormType {
  enumValues: string[];

}

export interface ServerFromDetailsSchemaPropValue {
  [key: string]: string | ServerFromDetailsSchemaPropValue
}

export interface ServerFormDetailsResponse {
  succeeded: boolean;
  result: { scheme: ServerFromDetailsSchemaPropValue }

}

export  enum ConvertServerFiledTypeToFormType {
  String = 'input',
  Date = 'datepicker',
  Enum = 'select'
}
