
// Generated by https://quicktype.io

export interface FormsTypeSchema {
  result: Result;
}

export interface Result {
  schemasList: SchemasList[];
}

export interface SchemasList {
  type:    string;
  display: string;
}

export interface SelectionOption {
   value: string, label: string
}

